apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: node-app
        image: nginx
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"      # 0.1 CPU guaranteed
            memory: "128Mi"  # minimum memory guaranteed

          limits:
            cpu: "500m"      # max CPU it can use
            memory: "256Mi"  # max memory allowed