apiVersion: v1
kind: Pod
metadata:
  name: backend-api
  labels:
    app: backend
spec:
  containers:
  - name: api
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: "kubernetes.io/hostname"