apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-small
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-small
  template:
    metadata:
      labels:
        app: app-small
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"