apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: ""
  volumeName: mysql-hostpath-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi