apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PASSWORD