apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-ebs-storage
  resources:
    requests:
      storage: 20Gi