apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: YWRtaW4= # Base64 encoded value of "admin"
  mongodb-password: Y29uc29sZQ== # Base64 encoded value of "console"