services:
  app:
    ports:
      - "3001:3000"

  grafana:
    ports:
      - "3000:3000"

  prometheus:
    ports:
      - "9090:9090"

  loki:
    ports:
      - "3100:3100"

  tempo:
    ports:
      - "3200:3200"